### ISSUE TITLE
Unable to rebuild linux

### ISSUE THREAD

**Issue by ccpplinux** [native-toolkit/lime#1493] opened 2021-11-05 20:13 UTC
When I am running the command "lime rebuild linux" then I am getting following error message:

Link: ../ndll/Linux64/lime.ndll
/usr/bin/ld: obj/linux64/0fd0c071_panning.o:(.rodata+0x13a0): multiple definition of `FuMa2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xea0): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_panning.o:(.rodata+0x13e0): multiple definition of `SN3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xee0): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_panning.o:(.rodata+0x1420): multiple definition of `N3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xf20): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_ALu.o:(.rodata+0x3bfa0): multiple definition of `FuMa2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xea0): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_ALu.o:(.rodata+0x3bfe0): multiple definition of `SN3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xee0): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_ALu.o:(.rodata+0x3c020): multiple definition of `N3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xf20): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_bformatdec.o:(.rodata+0x300): multiple definition of `SN3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xee0): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_bformatdec.o:(.rodata+0x340): multiple definition of `N3D2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xf20): first defined here
/usr/bin/ld: obj/linux64/0fd0c071_bformatdec.o:(.rodata+0x2c0): multiple definition of `FuMa2N3DScale'; obj/linux64/0fd0c071_ALc.o:(.rodata+0xea0): first defined here
collect2: error: ld returned 1 exit status

So I am not able to this package on my Linux laptop. Please help me what is going wrong here.

**Comment by player-03** [comment] 2021-11-05 20:25
Closing as a duplicate of native-toolkit/openal#5. See also native-toolkit/openal#6 for a workaround.

**Comment by player-03** [comment] 2021-11-06 18:28
And reopening to address the next error. Sorry for jumping around, I'm just trying to discuss each error in the correct repo.

> Thanks for giving me hint. After adding -fcommon flag when I executed then command lime rebuild linux -64 -release -clean then it executed successfully. However when I executed the command lime rebuild tools then following error messages were displayed:
> 
> ../src/lime/math/ColorMatrix.hx:117: characters 12-17 : lime.math.ColorMatrix should be Null<lime.utils.ArrayBufferView> ../src/lime/math/ColorMatrix.hx:117: characters 12-17 : ... For optional function argument 'view' ../src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext ../src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext ../src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext ../src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : ... For function argument 'params' ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : ... For function argument 'params' ../src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : lime.utils.UInt32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : lime.utils.UInt32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : lime.utils.UInt32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : lime.utils.Int32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : ... For function argument 'v' ../src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : lime.utils.UInt32Array should be lime.utils.DataPointer ../src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : ... For function argument 'v' ../src/lime/media/openal/AL.hx:1307: characters 3-11 : Int should be lime.media.openal.ALBuffer ../src/lime/media/OpenALAudioContext.hx:573: characters 3-40 : lime.media.openal.ALBuffer should be Int platforms/AndroidPlatform.hx:500: characters 19-51 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
> 
> Can you please specify a solution for it?

Are you by any chance using Lime 7.8.0? That one is missing some changes required by Haxe 4.2, including 59ddb96.

**Comment by player-03** [comment] 2021-11-17 08:38
Hey, just wondering if updating Lime fixed this.

**Closed** 2022-04-08 01:03 UTC
